image:
  repository: influxdb
  tag: 2.7.4-alpine

resources:
  limits:
    cpu: 500m
    memory: 4Gi
  requests:
    cpu: 250m
    memory: 2Gi

nodeSelector:
  cloud.google.com/gke-spot: "true"

startupProbe:
  enabled: true

persistence:
  size: 24Gi
