image:
  repository: influxdb
  tag: 2.6.0-alpine

resources:
  limits:
    cpu: 500m
    memory: 4Gi
  requests:
    cpu: 250m
    memory: 2Gi

nodeSelector:
  cloud.google.com/gke-spot: "true"

livenessProbe:
  failureThreshold: 3
  initialDelaySeconds: 0
  path: /health
  periodSeconds: 10
  scheme: HTTP
  timeoutSeconds: 1

readinessProbe:
  failureThreshold: 3
  initialDelaySeconds: 0
  path: /health
  periodSeconds: 10
  scheme: HTTP
  successThreshold: 1
  timeoutSeconds: 1

persistence:
  size: 10Gi
