apiVersion: skaffold/v2beta4
kind: Config
metadata:
  name: graph
build:
  artifacts:
  - image: asia.gcr.io/soul-weight/worker
    context: worker
deploy:
  kustomize:
    paths:
    - k8s/overlays/development
profiles:
- name: production
  deploy:
    kustomize:
      paths:
      - k8s/overlays/production
