apiVersion: skaffold/v1
kind: Config
metadata:
  name: graph
build:
  artifacts:
  - image: e2a4329a.azurecr.io/worker
    context: worker
deploy:
  kustomize:
    path: k8s/overlays/development
profiles:
- name: production
  patches:
  - op: replace
    path: /deploy/kustomize/path
    value: k8s/overlays/production
