image:
  repository: grafana/loki
  tag: 2.6.1

tracing:
  jaegerAgentHost: tempo

config:
  schema_config:
    configs:
    - from: 2022-06-19
      store: boltdb-shipper
      object_store: gcs
      schema: v11
      index:
        prefix: index_
        period: 24h
  storage_config:
    boltdb_shipper:
      shared_store: gcs
  compactor:
    shared_store: gcs

nodeSelector:
  cloud.google.com/gke-spot: "true"

resources:
  limits:
    cpu: 250m
    memory: 1Gi
  requests:
    cpu: 250m
    memory: 512m
