apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
spec:
  template:
    spec:
      containers:
      - name: grafana
        env:
        - name: GF_EXTERNAL_IMAGE_STORAGE_GCS_BUCKET
          valueFrom:
            secretKeyRef:
              name: gcs-credentials
              key: bucket
        - name: GF_EXTERNAL_IMAGE_STORAGE_GCS_KEY_FILE
          value: /var/secrets/google/key.json
        - name: GF_EXTERNAL_IMAGE_STORAGE_PROVIDER
          value: gcs
        - name: GF_SECURITY_COOKIE_SECURE
          value: "true"
        - name: GF_SECURITY_STRICT_TRANSPORT_SECURITY
          value: "true"
        - name: GF_SECURITY_STRICT_TRANSPORT_SECURITY_MAX_AGE_SECONDS
          value: "31536000"
        - name: GF_SECURITY_STRICT_TRANSPORT_SECURITY_PRELOAD
          value: "true"
        - name: GF_SECURITY_STRICT_TRANSPORT_SECURITY_SUBDOMAINS
          value: "true"
        - name: GF_SERVER_ENABLE_GZIP
          value: "true"
        - name: GF_SERVER_DOMAIN
          value: 21g.social
        - name: GF_SERVER_ENFORCE_DOMAIN
          value: "true"
        - name: GF_SERVER_ROOT_URL
          value: https://21g.social
        volumeMounts:
        - name: google-cloud-key
          mountPath: /var/secrets/google
      volumes:
      - name: google-cloud-key
        secret:
          secretName: gcs-key
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  annotations:
    beta.cloud.google.com/backend-config:
      '{"default": "grafana-backend-config"}'
    cloud.google.com/neg: '{"ingress": true}'
