apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: graph
  annotations:
    ingress.gcp.kubernetes.io/pre-shared-cert: graph-certificate, graph-old-certificate
    kubernetes.io/ingress.global-static-ip-name: graph-ip
