apiVersion: v1
kind: ConfigMap
metadata:
  name: telegraf-config
data:
  telegraf.conf: |
    # Configuration for telegraf agent
    [agent]
      ## Default data collection interval for all inputs
      interval = "10s"
      ## Rounds collection interval to 'interval'
      ## ie, if interval="10s" then always collect on :00, :10, :20, etc.
      round_interval = true

      ## Telegraf will send metrics to outputs in batches of at most
      ## metric_batch_size metrics.
      ## This controls the size of writes that Telegraf sends to output plugins.
      metric_batch_size = 1000

      ## For failed writes, telegraf will cache metric_buffer_limit metrics for each
      ## output, and will flush this buffer on a successful write. Oldest metrics
      ## are dropped first when this buffer fills.
      ## This buffer only fills when writes fail to output plugin(s).
      metric_buffer_limit = 10000

      ## Collection jitter is used to jitter the collection by a random amount.
      ## Each plugin will sleep for a random time within jitter before collecting.
      ## This can be used to avoid many plugins querying things like sysfs at the
      ## same time, which can have a measurable effect on the system.
      collection_jitter = "0s"

      ## Default flushing interval for all outputs. Maximum flush_interval will be
      ## flush_interval + flush_jitter
      flush_interval = "10s"
      ## Jitter the flush interval by a random amount. This is primarily to avoid
      ## large write spikes for users running a large number of telegraf instances.
      ## ie, a jitter of 5s and interval 10s means flushes will happen every 10-15s
      flush_jitter = "0s"

      ## By default or when set to "0s", precision will be set to the same
      ## timestamp order as the collection interval, with the maximum being 1s.
      ##   ie, when interval = "10s", precision will be "1s"
      ##       when interval = "250ms", precision will be "1ms"
      ## Precision will NOT be used for service inputs. It is up to each individual
      ## service input to set the timestamp at the appropriate precision.
      ## Valid time units are "ns", "us" (or "µs"), "ms", "s".
      precision = "s"

      ## Logging configuration:
      ## Run telegraf with debug log messages.
      debug = false
      ## Run telegraf in quiet mode (error log messages only).
      quiet = false
      ## Specify the log file name. The empty string means to log to stderr.
      logfile = ""

      ## Override default hostname, if empty use os.Hostname()
      hostname = ""
      ## If set to true, do no set the "host" tag in the telegraf agent.
      omit_hostname = true

    [[outputs.influxdb]]
      ## The full HTTP or UDP URL for your InfluxDB instance.
      ##
      ## Multiple URLs can be specified for a single cluster, only ONE of the
      ## urls will be written to each interval.
      # urls = ["unix:///var/run/influxdb.sock"]
      # urls = ["udp://127.0.0.1:8089"]
      # urls = ["http://127.0.0.1:8086"]
      urls = ["${INFLUXDB_URL}"]

      ## The target database for metrics; will be created as needed.
      ## For UDP url endpoint database needs to be configured on server side.
      database = "youtube"

      namepass = ["channel"]

    [[outputs.influxdb]]
      ## The full HTTP or UDP URL for your InfluxDB instance.
      ##
      ## Multiple URLs can be specified for a single cluster, only ONE of the
      ## urls will be written to each interval.
      # urls = ["unix:///var/run/influxdb.sock"]
      # urls = ["udp://127.0.0.1:8089"]
      # urls = ["http://127.0.0.1:8086"]
      urls = ["${INFLUXDB_URL}"]

      ## The target database for metrics; will be created as needed.
      ## For UDP url endpoint database needs to be configured on server side.
      database = "twitter"

      namepass = ["account"]

    [[outputs.health]]
      ## Address and port to listen on.
      ##   ex: service_address = "http://localhost:8080"
      ##       service_address = "unix:///var/run/telegraf-health.sock"
      service_address = "http://:8080"

    [[processors.enum]]
      [[processors.enum.mapping]]
        tag  = "id"
        dest = "group"

        [processors.enum.mapping.value_mappings]
          UC3EhsuKdEkI99TWZwZgWutg = "VApArt"     # 杏戸ゆげ
          UC0Owc36U9lOyi9Gx9Ic-4qg = "AniMare"    # 因幡はねる
          UCGiFzwdasSAHILrx-DB1pVQ = "AniMare"    # 稲荷くろむ
          UChqYnJlFxlBi6DfRz6jRenQ = "AniMare"    # 宇森ひなこ
          UC3xG1XWzAKt5dxSxktJvtxg = "AniMare"    # 大浦るかこ
          UCXp7sNC0F_qkjickvlYkg-Q = "AniMare"    # 風見くく
          UCmqrvfLMws-GLGHQcB5dasg = "VApArt"     # 花奏かのん
          UChXm-xAYPfygrbyLo2yCASQ = "VApArt"     # 季咲あんこ
          UC0xhrAce06OkQfHBqAfLQAQ = "AniMare"    # 奇想天外あにびっと!
          UCjm74OvxjKhpGOj1DP117kQ = "AniMare"    # きまぐれ委員会
          UCr83W-PdmmbstrvnCn9kdZQ = "VApArt"     # 銀猫ななし
          UC8BS2IrE9NmxKLX7ObRVyxQ = "AniMare"    # 黒猫ななし
          UCvPPBoTOor5gm8zSlE2tg4w = "SugarLyric" # 虎城アンナ
          UC4PrHgUcAtOoj_LKmUL-uLQ = "AniMare"    # 湖南みあ
          UCzUNASdzI4PV5SlqtYwAkKQ = "VApArt"     # 小森めと
          UCwePpiw1ocZRSNSkpKvVISw = "HoneyStrap" # 西園寺メアリ
          UC--A2dwZW7-M2kID0N6_lfA = "SugarLyric" # 獅子王クリス
          UCYTz3uIgwVY3ZU-IQJS8r3A = "HoneyStrap" # 島村シャルロット
          UCtzCQnCT9E4o6U3mHHSHbQQ = "AniMare"    # 白宮みみ
          UCeLzT-7b2PBcunJplmWtoDg = "HoneyStrap" # 周防パトラ
          UCDh2bWI5EDu7PavqwICkVpA = "HoneyStrap" # 堰代ミコ
          UC_WOBIopwUih0rytRnr_1Ag = "AniMare"    # 瀬島るい
          UC2kyQhzGOB-JPgcQX9OMgEw = "AniMare"    # 宗谷いちか
          UC3UKMRQmBcjXWu66cvxcngA = "HoneyStrap" # 蒼月エリ
          UCqskJ0nmw-_eweWfsKvbrzQ = "AniMare"    # 月野木ちろる
          UCgqQ5iuvUyPRHp3rBLuOtCw = "HoneyStrap" # 灰猫ななし
          UCOgONfZgrG2g0jntQKa6cDw = "AniMare"    # 灰原あかね
          UC_BlXOQe5OcRC7o0GX8kp8A = "AniMare"    # 羽柴なつみ
          UCRvpMpzAXBRKJQuk-8-Sdvg = "AniMare"    # 日ノ隈らん
          UCFsWaTQ7kT76jNNGeGIKNSA = "AniMare"    # 飛良ひかり
          UCV4EoK6BVNl7wxuxpUvvSWA = "VApArt"     # 不磨わっと
          UCoieZAlwgK3uLkIYiJARDQw = "SugarLyric" # 三毛猫ななし
          UCTsEofJvQymp0Dcd4wYBmVQ = "AniMare"    # 桃乃ゆらり
          UCW8WKciBixmaqaGqrlTITRQ = "AniMare"    # 柚原いづみ
          UC2hc-00y-MSR6eYA4eQ4tjQ = "SugarLyric" # 龍ヶ崎リン

      [[processors.enum.mapping]]
        tag     = "id"
        dest    = "retired"
        default = false

        [processors.enum.mapping.value_mappings]
          UCGiFzwdasSAHILrx-DB1pVQ = true # 稲荷くろむ
          UC3UKMRQmBcjXWu66cvxcngA = true # 蒼月エリ
          UChqYnJlFxlBi6DfRz6jRenQ = true # 宇森ひなこ
          UCTsEofJvQymp0Dcd4wYBmVQ = true # 桃乃ゆらり
          UCOgONfZgrG2g0jntQKa6cDw = true # 灰原あかね
          UC_BlXOQe5OcRC7o0GX8kp8A = true # 羽柴なつみ

      [[processors.enum.mapping]]
        tag  = "id"
        dest = "group"

        [processors.enum.mapping.value_mappings]
          992355895051866100  = "VApArt"     # _kanade_kanon
          993839162099810300  = "AniMare"    # AniMare_cafe
          995247053977485300  = "AniMare"    # Haneru_Inaba
          995250952373391400  = "AniMare"    # Hinako_Umori
          995253301472972800  = "AniMare"    # Ichika_Souya
          995258822556991500  = "AniMare"    # Ran_Hinokuma
          1007247110167674900 = "HoneyStrap" # HNST_official
          1007268292648505300 = "HoneyStrap" # Patra_HNST
          1007290563756871700 = "HoneyStrap" # Eli_HNST
          1007316805981892600 = "HoneyStrap" # Charlotte_HNST
          1007331251685023700 = "HoneyStrap" # Mary_HNST
          1007339408343777300 = "HoneyStrap" # Mico_HNST
          1091634367158337500 = "VApArt"     # Vtuber_ApArt
          1091649332539846700 = "VApArt"     # Uge_And
          1113405297949700100 = "AniMare"    # tirol0_0lorit
          1128841181222203400 = "AniMare"    # shiromiya_mimi
          1184117947582697500 = "VApArt"     # Anko_Kisaki
          1224952244719587300 = "AniMare"    # Kuku_Kazami
          1224956450100764700 = "AniMare"    # Izumi_Yunohara
          1234696406931136500 = "SugarLyric" # Anna_Kojo
          1234697406542803000 = "SugarLyric" # Rene_Ryugasaki
          1234698396297859000 = "SugarLyric" # SugarLyric_PI
          1240652791892172800 = "SugarLyric" # ChrisShishio
          1245694490532176000 = "AniMare"    # Natsumi_Hashiba
          1245695747602837500 = "AniMare"    # Yurari_Momono
          1245697015066984400 = "AniMare"    # Akane_Haibara
          1248507657226313700 = "AniMare"    # KisoAnibit
          1258264128780554200 = "VApArt"     # Met_Komori
          1258264848011366400 = "VApArt"     # Wat_Huma
          1308626156447436800 = "AniMare"    # Rui_Seshima
          1308632177815421000 = "AniMare"    # Hikari_Hira
          1351387644081520600 = "AniMare"    # Rukako_Oura
          1351423100026425300 = "AniMare"    # Mia_Konan
          1397780980597883000 = "AniMare"    # kimagureiinkai
          1414380215002747000 = "774inc"     # 774inc_vacation
          1445646417385574400 = "HIYOCRO"    # Sei_Touri
          1445646752430784500 = "HIYOCRO"    # Nemo_Suzumi
          1445647446638399500 = "HIYOCRO"    # Canna_Akane
          1445647483925717000 = "HIYOCRO"    # Popo_Ieiri
          1445647873882742800 = "HIYOCRO"    # Kiki_Shisui
          1445647957412384800 = "HIYOCRO"    # Yuri_Kohakuu
          1448968028972933000 = "HIYOCRO"    # HIYOCRO_PT

      [[processors.enum.mapping]]
        tag     = "id"
        dest    = "retired"
        default = false

        [processors.enum.mapping.value_mappings]
          995250952373391400  = true # Hinako_Umori
          1007290563756871700 = true # Eli_HNST
          1245694490532176000 = true # Natsumi_Hashiba
          1245695747602837500 = true # Yurari_Momono
          1245697015066984400 = true # Akane_Haibara

    [[inputs.execd]]
      name_override = "channel"

      command = ["youtube-telegraf-plugin", "-config", "/etc/telegraf/youtube-telegraf-plugin.conf"]
      signal = "none"

    [[inputs.execd]]
      name_override = "account"

      command = ["twitter-telegraf-plugin", "-config", "/etc/telegraf/twitter-telegraf-plugin.conf"]
      signal = "none"

  youtube-telegraf-plugin.conf: |
    # YouTube Telegraf Plugin Configuration

    [[inputs.youtube]]
      ## List of channels to monitor.
      channels = [
        "UC3EhsuKdEkI99TWZwZgWutg", # 杏戸ゆげ
        "UC0Owc36U9lOyi9Gx9Ic-4qg", # 因幡はねる
        "UCGiFzwdasSAHILrx-DB1pVQ", # 稲荷くろむ
        "UChqYnJlFxlBi6DfRz6jRenQ", # 宇森ひなこ
        "UC3xG1XWzAKt5dxSxktJvtxg", # 大浦るかこ
        "UCXp7sNC0F_qkjickvlYkg-Q", # 風見くく
        "UCmqrvfLMws-GLGHQcB5dasg", # 花奏かのん
        "UChXm-xAYPfygrbyLo2yCASQ", # 季咲あんこ
        "UC0xhrAce06OkQfHBqAfLQAQ", # 奇想天外あにびっと!
        "UCjm74OvxjKhpGOj1DP117kQ", # きまぐれ委員会
        "UCr83W-PdmmbstrvnCn9kdZQ", # 銀猫ななし
        "UC8BS2IrE9NmxKLX7ObRVyxQ", # 黒猫ななし
        "UCvPPBoTOor5gm8zSlE2tg4w", # 虎城アンナ
        "UC4PrHgUcAtOoj_LKmUL-uLQ", # 湖南みあ
        "UCzUNASdzI4PV5SlqtYwAkKQ", # 小森めと
        "UCwePpiw1ocZRSNSkpKvVISw", # 西園寺メアリ
        "UC--A2dwZW7-M2kID0N6_lfA", # 獅子王クリス
        "UCYTz3uIgwVY3ZU-IQJS8r3A", # 島村シャルロット
        "UCtzCQnCT9E4o6U3mHHSHbQQ", # 白宮みみ
        "UCeLzT-7b2PBcunJplmWtoDg", # 周防パトラ
        "UCDh2bWI5EDu7PavqwICkVpA", # 堰代ミコ
        "UC_WOBIopwUih0rytRnr_1Ag", # 瀬島るい
        "UC2kyQhzGOB-JPgcQX9OMgEw", # 宗谷いちか
        "UC3UKMRQmBcjXWu66cvxcngA", # 蒼月エリ
        "UCqskJ0nmw-_eweWfsKvbrzQ", # 月野木ちろる
        "UCgqQ5iuvUyPRHp3rBLuOtCw", # 灰猫ななし
        "UCOgONfZgrG2g0jntQKa6cDw", # 灰原あかね
        "UC_BlXOQe5OcRC7o0GX8kp8A", # 羽柴なつみ
        "UCRvpMpzAXBRKJQuk-8-Sdvg", # 日ノ隈らん
        "UCFsWaTQ7kT76jNNGeGIKNSA", # 飛良ひかり
        "UCV4EoK6BVNl7wxuxpUvvSWA", # 不磨わっと
        "UCoieZAlwgK3uLkIYiJARDQw", # 三毛猫ななし
        "UCTsEofJvQymp0Dcd4wYBmVQ", # 桃乃ゆらり
        "UCW8WKciBixmaqaGqrlTITRQ", # 柚原いづみ
        "UC2hc-00y-MSR6eYA4eQ4tjQ"  # 龍ヶ崎リン
      ]

      ## Google API key.
      api_key = "${GOOGLE_API_KEY}"

  twitter-telegraf-plugin.conf: |
    # Twitter Telegraf Plugin Configuration

    [[inputs.twitter]]
    ## List of accounts to monitor.
    accounts = [
      992355895051866100,  # _kanade_kanon
      993839162099810300,  # AniMare_cafe
      995247053977485300,  # Haneru_Inaba
      995250952373391400,  # Hinako_Umori
      995253301472972800,  # Ichika_Souya
      995258822556991500,  # Ran_Hinokuma
      1007247110167674900, # HNST_official
      1007268292648505300, # Patra_HNST
      1007290563756871700, # Eli_HNST
      1007316805981892600, # Charlotte_HNST
      1007331251685023700, # Mary_HNST
      1007339408343777300, # Mico_HNST
      1091634367158337500, # Vtuber_ApArt
      1091649332539846700, # Uge_And
      1113405297949700100, # tirol0_0lorit
      1128841181222203400, # shiromiya_mimi
      1184117947582697500, # Anko_Kisaki
      1224952244719587300, # Kuku_Kazami
      1224956450100764700, # Izumi_Yunohara
      1234696406931136500, # Anna_Kojo
      1234697406542803000, # Rene_Ryugasaki
      1234698396297859000, # SugarLyric_PI
      1240652791892172800, # ChrisShishio
      1245694490532176000, # Natsumi_Hashiba
      1245695747602837500, # Yurari_Momono
      1245697015066984400, # Akane_Haibara
      1248507657226313700, # KisoAnibit
      1258264128780554200, # Met_Komori
      1258264848011366400, # Wat_Huma
      1308626156447436800, # Rui_Seshima
      1308632177815421000, # Hikari_Hira
      1351387644081520600, # Rukako_Oura
      1351423100026425300, # Mia_Konan
      1397780980597883000, # kimagureiinkai
      1414380215002747000, # 774inc_vacation
      1445646417385574400, # Sei_Touri
      1445646752430784500, # Nemo_Suzumi
      1445647446638399500, # Canna_Akane
      1445647483925717000, # Popo_Ieiri
      1445647873882742800, # Kiki_Shisui
      1445647957412384800, # Yuri_Kohakuu
      1448968028972933000  # HIYOCRO_PT
    ]
    ## Twitter API consumer key.
    consumer_key = "${TWITTER_CONSUMER_KEY}"
    ## Twitter API consumer secret.
    consumer_secret = "${TWITTER_CONSUMER_SECRET}"
    ## Twitter API access token.
    access_token = "${TWITTER_ACCESS_TOKEN}"
    ## Twitter API access token secret.
    access_token_secret = "${TWITTER_ACCESS_TOKEN_SECRET}"
