image:
  repository: grafana/promtail
  tag: 2.5.0

resources:
  limits:
    cpu: 200m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

nodeSelector:
  cloud.google.com/gke-spot: "true"

defaultVolumes:
- name: containers
  emptyDir: {}
- name: pods
  emptyDir: {}

config:
  clients:
  - url: http://loki:3031/loki/api/v1/push
  snippets:
    common:
    - action: replace
      source_labels:
      - __meta_kubernetes_pod_node_name
      target_label: node_name
    - action: replace
      source_labels:
      - __meta_kubernetes_namespace
      target_label: namespace
    - action: replace
      replacement: $1
      separator: /
      source_labels:
      - namespace
      - app
      target_label: job
    - action: replace
      source_labels:
      - __meta_kubernetes_pod_name
      target_label: pod
    - action: replace
      source_labels:
      - __meta_kubernetes_pod_container_name
      target_label: container
