image:
  repository: grafana/promtail
  tag: 2.6.1

resources:
  limits:
    cpu: 200m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

nodeSelector:
  cloud.google.com/gke-spot: "true"

defaultVolumes:
- name: run
  emptyDir: {}
- name: pods
  hostPath:
    path: /var/log/pods

defaultVolumeMounts:
- name: run
  mountPath: /run/promtail
- name: pods
  mountPath: /var/log/pods
  readOnly: true

config:
  clients:
  - url: http://loki:3100/loki/api/v1/push
