autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 8
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 60
  - type: Resource
    resource:
      name: memory
      targetAverageUtilization: 60

podDisruptionBudget:
  minAvailable: 2

image:
  repository: grafana/grafana
  tag: 10.0.4

rbac:
  pspEnabled: false

testFramework:
  enabled: false

service:
  annotations:
    beta.cloud.google.com/backend-config:
      '{"default": "grafana-backend-config"}'
    cloud.google.com/neg: '{"ingress": true}'

extraExposePorts:
- name: grafana-unified-alerting-tcp
  protocol: TCP
  port: 9094
  targetPort: 9094
- name: grafana-unified-alerting-udp
  protocol: UDP
  port: 9094
  targetPort: 9094

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.global-static-ip-name: graph-ip
    networking.gke.io/managed-certificates: graph-certificate
    networking.gke.io/v1beta1.FrontendConfig: grafana-frontend-config
  hosts:
  - 21g.social
  - www.21g.social

resources:
  limits:
    cpu: 250m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 512Mi

nodeSelector:
  cloud.google.com/gke-spot: "true"

env:
  GF_ALERTING_ENABLED: "false"
  GF_AUTH_ANONYMOUS_ENABLED: "true"
  GF_AUTH_ANONYMOUS_ORG_NAME: Haneru Developers
  GF_FEATURE_TOGGLES_ENABLE: publicDashboards
  GF_SECURITY_COOKIE_SECURE: "true"
  GF_SECURITY_STRICT_TRANSPORT_SECURITY: "true"
  GF_SECURITY_STRICT_TRANSPORT_SECURITY_MAX_AGE_SECONDS: "31536000"
  GF_SECURITY_STRICT_TRANSPORT_SECURITY_PRELOAD: "true"
  GF_SECURITY_STRICT_TRANSPORT_SECURITY_SUBDOMAINS: "true"
  GF_SERVER_ENABLE_GZIP: "true"
  GF_SERVER_DOMAIN: 21g.social
  GF_SERVER_ENFORCE_DOMAIN: "true"
  GF_SERVER_ROOT_URL: https://21g.social
  GF_SNAPSHOTS_EXTERNAL_ENABLED: "false"
  GF_DATAPROXY_TIMEOUT: "120"
  GF_UNIFIED_ALERTING_ENABLED: "true"
  GF_UNIFIED_ALERTING_HA_LISTEN_ADDRESS: ${POD_IP}:9094
  GF_UNIFIED_ALERTING_HA_PEERS: grafana:9094
  GF_UNIFIED_ALERTING_SCREENSHOTS_CAPTURE: "true"
  GF_UNIFIED_ALERTING_SCREENSHOTS_UPLOAD_EXTERNAL_IMAGE_STORAGE: "true"

envValueFrom:
  POD_IP:
    fieldRef:
      fieldPath: status.podIP

envFromSecret: grafana-tokens

datasources:
  datasources.yaml:
    apiVersion: 1

    deleteDatasources:
    - name: Twitter
      orgId: 1

imageRenderer:
  enabled: true
  image:
    repository: grafana/grafana-image-renderer
    tag: 3.7.2
  env:
    BROWSER_TZ: Asia/Tokyo
    ENABLE_METRICS: "true"
    RENDERING_CLUSTERING_MAX_CONCURRENCY: "3"
    RENDERING_CLUSTERING_MODE: contextPerRenderKey
    RENDERING_CLUSTERING_TIMEOUT: "30"
    RENDERING_MODE: clustered
  networkPolicy:
    limitIngress: false
  resources:
    limits:
      cpu: 1000m
      memory: 4Gi
    requests:
      cpu: 500m
      memory: 4Gi
  nodeSelector:
    cloud.google.com/gke-spot: "true"

extraObjects:
- apiVersion: networking.gke.io/v1
  kind: ManagedCertificate
  metadata:
    name: graph-certificate
  spec:
    domains:
    - 21g.social
    - www.21g.social
- apiVersion: networking.gke.io/v1beta1
  kind: FrontendConfig
  metadata:
    name: grafana-frontend-config
  spec:
    redirectToHttps:
      enabled: true
      responseCodeName: PERMANENT_REDIRECT
- apiVersion: cloud.google.com/v1beta1
  kind: BackendConfig
  metadata:
    name: grafana-backend-config
  spec:
    cdn:
      enabled: true
      cachePolicy:
        includeHost: true
        includeProtocol: true
        includeQueryString: true
    timeoutSec: 120
