autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 60
  - type: Resource
    resource:
      name: memory
      targetAverageUtilization: 60

podDisruptionBudget:
  minAvailable: 1

image:
  repository: grafana/grafana
  tag: 9.0.1

testFramework:
  enabled: false

service:
  annotations:
    beta.cloud.google.com/backend-config:
      '{"default": "grafana-backend-config"}'
    cloud.google.com/neg: '{"ingress": true}'

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.global-static-ip-name: graph-ip
    networking.gke.io/managed-certificates: graph-certificate
    networking.gke.io/v1beta1.FrontendConfig: grafana-frontend-config
  hosts:
  - 21g.social
  - www.21g.social

resources:
  limits:
    cpu: 250m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 512Mi

nodeSelector:
  cloud.google.com/gke-spot: "true"

env:
  GF_ALERTING_ENABLED: "false"
  GF_AUTH_ANONYMOUS_ENABLED: "true"
  GF_AUTH_ANONYMOUS_ORG_NAME: Haneru Developers
  GF_SECURITY_COOKIE_SECURE: "true"
  GF_SECURITY_STRICT_TRANSPORT_SECURITY: "true"
  GF_SECURITY_STRICT_TRANSPORT_SECURITY_MAX_AGE_SECONDS: "31536000"
  GF_SECURITY_STRICT_TRANSPORT_SECURITY_PRELOAD: "true"
  GF_SECURITY_STRICT_TRANSPORT_SECURITY_SUBDOMAINS: "true"
  GF_SERVER_ENABLE_GZIP: "true"
  GF_SERVER_DOMAIN: 21g.social
  GF_SERVER_ENFORCE_DOMAIN: "true"
  GF_SERVER_ROOT_URL: https://21g.social
  GF_SNAPSHOTS_EXTERNAL_ENABLED: "false"
  GF_DATAPROXY_TIMEOUT: "120"
  GF_UNIFIED_ALERTING_ENABLED: "true"
  GF_UNIFIED_ALERTING_SCREENSHOTS_CAPTURE: "true"
  GF_UNIFIED_ALERTING_SCREENSHOTS_UPLOAD_EXTERNAL_IMAGE_STORAGE: "true"

envFromSecret: grafana-tokens

datasources:
  datasources.yaml:
    apiVersion: 1

    deleteDatasources:
    - name: Twitter
      orgId: 1

imageRenderer:
  enabled: true
  image:
    repository: grafana/grafana-image-renderer
    tag: 3.4.2
  env:
    BROWSER_TZ: Asia/Tokyo
    # https://github.com/grafana/grafana-image-renderer/issues/124#issuecomment-606494641
    RENDERING_ARGS: --no-sandbox,--disable-setuid-sandbox,--disable-dev-shm-usage,--disable-accelerated-2d-canvas,--disable-gpu,--window-size=1920x1080
    RENDERING_CLUSTERING_MODE: contextPerRenderKey
    RENDERING_MODE: clustered
  networkPolicy:
    limitIngress: false
  resources:
    limits:
      cpu: 250m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 512Mi
  nodeSelector:
    cloud.google.com/gke-spot: "true"

extraObjects:
- apiVersion: networking.gke.io/v1
  kind: ManagedCertificate
  metadata:
    name: graph-certificate
  spec:
    domains:
    - 21g.social
    - www.21g.social
- apiVersion: networking.gke.io/v1beta1
  kind: FrontendConfig
  metadata:
    name: grafana-frontend-config
  spec:
    redirectToHttps:
      enabled: true
      responseCodeName: PERMANENT_REDIRECT
- apiVersion: cloud.google.com/v1beta1
  kind: BackendConfig
  metadata:
    name: grafana-backend-config
  spec:
    cdn:
      enabled: true
      cachePolicy:
        includeHost: true
        includeProtocol: true
        includeQueryString: true
    timeoutSec: 120
