apiVersion: cloud.google.com/v1beta1
kind: BackendConfig
metadata:
  name: grafana-backend-config
spec:
  cdn:
    enabled: true
    cachePolicy:
      includeHost: false
      includeProtocol: true
      includeQueryString: false
