apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
 name: letsencrypt
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: contact@haneru.dev
    privateKeySecretRef:
      name: letsencrypt
    solvers:
    - http01:
        ingress:
          class: traefik
