apiVersion: v1
kind: Service
metadata:
  name: influxdb2
  labels:
    app: influxdb2
spec:
  selector:
    app: influxdb2
  ports:
  - protocol: TCP
    port: 8086
    targetPort: 8086
  clusterIP: None
