apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: influxdb
  labels:
    app: influxdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: influxdb
  serviceName: influxdb
  template:
    metadata:
      labels:
        app: influxdb
    spec:
      containers:
      - name: influxdb
        image: influxdb:2.0.9-alpine
        env:
        - name: DOCKER_INFLUXDB_INIT_MODE
          value: upgrade
        - name: DOCKER_INFLUXDB_INIT_USERNAME
          value: ykzts
        - name: DOCKER_INFLUXDB_INIT_PASSWORD
          value: pppp1234
        - name: DOCKER_INFLUXDB_INIT_ORG
          value: inabagumi
        - name: DOCKER_INFLUXDB_INIT_BUCKET
          value: default
        - name: DOCKER_INFLUXDB_INIT_ADMIN_TOKEN
          valueFrom:
            secretKeyRef:
              name: influxdb-credentials
              key: token
        ports:
        - containerPort: 8086
        volumeMounts:
        - mountPath: /var/lib/influxdb
          name: influxdb-data
        volumeMounts:
        - mountPath: /var/lib/influxdb2
          name: influxdb-data
        livenessProbe:
          httpGet:
            port: 8086
            path: /ping
          initialDelaySeconds: 30
          periodSeconds: 5
        readinessProbe:
          httpGet:
            port: 8086
            path: /ping
          initialDelaySeconds: 10
          periodSeconds: 5
  volumeClaimTemplates:
  - metadata:
      name: influxdb-data
      labels:
        app: influxdb
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi
  - metadata:
      name: influxdb2-data
      labels:
        app: influxdb
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi
