name: Deploy to k8s cluster

on:
  push:
    branches:
    - master

env:
  KUSTOMIZE_VERSION: 2.1.0
  SKAFFOLD_VERSION: 1.0.1
  SKAFFOLD_PROFILE: production

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Set up Kustomize
      run: |
        curl -Lo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v${KUSTOMIZE_VERSION}/kustomize_${KUSTOMIZE_VERSION}_linux_amd64
        sudo install kustomize /usr/local/bin
    - name: Set up Skaffold
      run: |
        curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/v${SKAFFOLD_VERSION}/skaffold-linux-amd64
        sudo install skaffold /usr/local/bin
    - uses: Azure/docker-login@v1
      with:
        login-server: e2a4329a.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - uses: Azure/k8s-set-context@v1
      with:
        kubeconfig: ${{ secrets.KUBE_CONFIG }}
    - name: Build, and Publish
      run: |
        skaffold build --file-output tags.json
    - name: Deploy
      run: |
        skaffold deploy --build-artifacts tags.json --status-check
