apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-image-renderer
  labels:
    app: grafana-image-renderer
spec:
  selector:
    matchLabels:
      app: grafana-image-renderer
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: grafana-image-renderer
    spec:
      containers:
      - name: grafana-image-renderer
        image: grafana/grafana-image-renderer:3.3.0
        env:
        - name: BROWSER_TZ
          value: Asia/Tokyo
        ports:
        - containerPort: 8081
        livenessProbe:
          httpGet:
            port: 8081
            path: /
          initialDelaySeconds: 15
          periodSeconds: 5
        readinessProbe:
          httpGet:
            port: 8081
            path: /
          initialDelaySeconds: 15
          periodSeconds: 5
